import logging
path=input("Enter the path:")
logger=logging.getLogger(__name__)
fhandler = logging.FileHandler(filename=path,mode="w")
fhandler.setLevel(logging.WARNING)
formatter = logging.Formatter('%(asctime)s:%(levelname)s:%(name)s:%(message)s')
fhandler.setFormatter(formatter)
logger.addHandler(fhandler)
logger.debug("debug")
logger.info("info")
logger.warning("warning")
logger.error("error")
logger.critical("critical")
